# Generated by Django 4.2.7 on 2023-12-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(default=1, upload_to='laptop_image/'),
            preserve_default=False,
        ),
    ]
